name: run-e2e-tests
on:
  workflow_dispatch: {}
jobs:
  end-to-end-and-packaging:
    runs-on: ubuntu-latest
    name: E2E test & packaging - nodejs${{ matrix.version }}x - ${{ matrix.package }}
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    strategy:
      matrix:
        version: [ 14 ]
        package: [ logger, metrics, tracer ]
    concurrency:
      group: e2e-tests-${{ matrix.version }}-${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: eu-central-1
      - name: "Setup Node.js ${{ matrix.version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Run tests
        run: |
          npm ci --foreground-scripts
          NODE_VERSION=${{ matrix.version }} npm run test:e2e:${{ matrix.package }}
      - name: Install example packages
        # Since we are not managing the cdk examples with npm workspaces we install
        # the dependencies in a separate step
        working-directory: ./examples/cdk
        run: npm ci
      - name: Run packaging tests
        working-directory: ~
        run: |
          npm run lerna-package
          cd examples/cdk
          npm install ../../packages/**/dist/aws-lambda-powertools-*
          npm run test