name: run-e2e-tests
on:
  workflow_dispatch: {}
jobs:
  end-to-end-and-packaging:
    runs-on: ubuntu-latest
    name: E2E test & packaging - ${{ matrix.version }} - ${{ matrix.utility }}
    strategy:
      matrix:
        version: [ 14 ]
        utility: [ logger, metrics, tracing ]
        fail
    concurrency:
      group: e2e-tests-${{ matrix.version }}-${{ matrix.utility }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: eu-west-1
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Node.js ${{ matrix.version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install monorepo packages
        # This installs all the dependencies of ./packages/*
        # See https://github.com/npm/cli/issues/4475 to see why --foreground-scripts
        run: npm ci --foreground-scripts
      - name: Install example packages
        # Since we are not managing the cdk examples with npm workspaces we install
        # the dependencies in a separate step
        working-directory: ./examples/cdk
        run: npm ci
      - name: Run integration tests
        run: |
          cd packages/${{ matrix.utility }}
          npm run lerna-package
          cd examples/cdk
      - name: Run packaging tests
        run: |
          cd ~
          npm run lerna-package
          cd examples/cdk
          npm install ../../packages/**/dist/aws-lambda-powertools-*
          npm run test